
dataset:
  name: 'Cephalometric'
  pth: '/home1/quanquan/datasets/Cephalometric/'
  n_cls: 19
special:
  num_landmarks: 19
  lambda: 2
  regress: true  # Regression module
  non_local: true
#  patch_size: 384
  emb_len: 16
  nearby: 9

# ------------------------------------------------
base:
  base_dir: "/home1/quanquan/code/landmark/code/runs/ana/"
  experiment: 'ssl'
  tag: ''
  stage: ''
logger:
  mode: ['tb', ]
#  mode: ''
  recorder_reduction: 'mean'

training:
  #  gpus: '0,1,6,7'
  ddp:
    master_addr: 'localhost'
    master_port: '25807'
  batch_size : 8
  num_workers : 8
  num_epochs : 5  # epochs
  use_amp: false
  save_interval : 50
  val_check_interval: 10
  load_pretrain_model: false
  lr: 0.000

  # betas:
  decay_step: 50
  decay_gamma: 0.8
  weight_decay: 0.0001
  alpha: 0.99
  #  pretrained_model: None
