base:
  base_dir: "/home1/quanquan/code/landmark/code/runs/ssl/"
  experiment: 'ssl'
  tag: ''
  stage: ''
logger:
#  mode: ['tb', ]
  mode: ''
  recorder_reduction: 'sum'

dataset:
  name: 'Cephalometric'
  pth: '/home1/quanquan/datasets/Cephalometric/'
  n_cls: 19

dataset2:
  name: 'Cephalometric'
  pth: '/home1/quanquan/datasets/hand/hand/'
  n_cls: 37

special:
  num_landmarks: 19
  lambda: 2
  regress: true  # Regression module
  # Important Params
  non_local: true
  patch_size: 256
  emb_len: 16
  nearby: 9

training:
#  gpus: '0,1,6,7'
  ddp:
    master_addr: 'localhost'
    master_port: '25807'
  batch_size : 8
  num_workers : 8
  num_epochs : 2500  # epochs
  use_amp: true
  save_interval : 200
  val_check_interval: 100
  lr: 0.00001
  decay_step: 100
  decay_gamma: 0.8
  # betas:
  weight_decay: 0.0001
  alpha: 0.99
  load_pretrain_model: false

#network:
#  pretrain: '/home1/quanquan/code/landmark/code/runs_tr/std5/best_model_epoch_1850.pth'
