base:
  base_dir: "/home1/quanquan/code/landmark/code/runs/baseline/"
  experiment: 'baseline_v0'
  tag: ''
  stage: ''
logger:
  mode: ['tb', ]

dataset:
  name: 'Cephalometric'
  pth: '/home1/quanquan/datasets/Cephalometric/'
  n_cls: 19
special:
  num_landmarks: 19
  emb_len: 16
  nearby : 6
  alpha: 0.99
  lambda: 2
  regress: false  # Regression module
training:
  gpus: '2,3'
  ddp:
    master_addr: 'localhost'
    master_port: '25707'
  batch_size : 16
  num_workers : 16
  num_epochs : 1000  # epochs
  use_amp: false
  save_interval : 50
  val_check_interval: 50
  decay_step: 200
  decay_gamma: 0.8
  lr: 0.0001
  weight_decay: 0.0001
  load_pretrain_model: false

#network:
#  pretrain: '/home1/quanquan/code/landmark/code/runs_tr/std5/best_model_epoch_1850.pth'
