
dataset:
  name: 'Cephalometric'
  pth: '/home1/quanquan/datasets/Cephalometric/'
  n_cls: 19
special:
  num_landmarks: 19
  lambda: 2
  regress: true  # Regression module

base:
  base_dir: "/home1/quanquan/code/landmark/code/runs/self_train/"
  experiment: 'self_train'
  tag: ''
  stage: ''
logger:
  #  mode: ['tb', ]
  mode: ''


training:
  batch_size: 16
  num_workers: 0
  num_landmarks: 19
  lr: 0.0003 # 0.00001
  decay_step: 50
  decay_gamma: 0.
  num_epochs: 100
  save_seq: 10
  lambda: 2
  #  gpus: '0,1,6,7'

  ddp:
    master_addr: 'localhost'
    master_port: '25807'
  use_amp: false
  save_interval : 50
  val_check_interval: 10
  # betas:
  weight_decay: 0.0001
  alpha: 0.99
  load_pretrain_model: true

  # Important Params
  non_local: true
  patch_size: 256
  emb_len: 16
  nearby: 9

