base:
  base_dir: "/home1/quanquan/code/landmark/code/runs/inc/"
  experiment: 'inc_v0'
  tag: ''
  stage: ''
logger:
  mode: ['tb', ]

dataset:
  name: 'Cephalometric'
  pth: '/home1/quanquan/datasets/Cephalometric/'
  n_cls: 19
special:
  num_landmarks: 19
  emb_len: 16
  nearby : 6
  alpha: 0.99
  lambda: 2
  regress: true  # Regression module
training:
  gpus: '0,1,6,7'
  ddp:
    master_addr: 'localhost'
    master_port: '25707'
  batch_size : 16
  num_workers : 16
  num_epochs : 2500  # epochs
  use_amp: false
  save_interval : 50
  val_check_interval: 50
  decay_step: 50
  decay_gamma: 0.8
  lr: 0.001
  weight_decay: 0.000

network:
  pretrain: '/home1/quanquan/code/landmark/code/runs_tr/std5/best_model_epoch_1850.pth'
