

base:
  base_dir: "../runs-ana/"
  experiment: 'semi_train'
  stage: ''
  gpus: '-2'
logger:
  mode: ''


dataset:
  pth : '/home1/quanquan/datasets/Cephalometric/'

training:
  batch_size : 8
  num_workers : 8
  num_landmarks : 19
  learning_rate : 0.00001
  decay_step : 50
  decay_gamma : 0.8
  num_epochs : 200
  save_seq : 10
  nearby : 8
  lambda : 2
  alpha : 0.99
  non_local: True
  conf: False
  # Contrast with cconf.yaml
  patch_size: 256
  emb_len: 16
other:
  other: ''

num_ref: 10